[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort
    "PL", # pylint (subset)
]
line-length = 88
extend-ignore = [
    "PLR",  # Design related pylint codes
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88
target-version = ['py313']